#can be many wiki & many www sites

[server]
port = 3000
addr = "0.0.0.0"


[[wiki]]
name = "wiki_bettertoken"
title = "Grid Manual"
url = "https://github.com/BetterToken/info_bettertoken.git"
path = ""
autocommit = false
branch = "master"
branchswitch = false
srcdir = "src"
environment = "production"
domain = "wiki.bettertoken.com"

